import Navbar from '@/components/Navbar'
import Sidebar from '@/components/Sidebar'
import { authOptions } from '@/lib/auth'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import { Inter } from 'next/font/google'
import { PropsWithChildren } from 'react'
import { ToastContainer } from 'react-toastify'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = async ({ children }: PropsWithChildren) => {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col flex-1 min-h-screen">
          <Navbar />
          <div className="flex-1 flex bg-base-300">
            {session?.user && <Sidebar />}
            {children}
          </div>
        </div>
        <ToastContainer />
      </body>
    </html>
  )
}

export default RootLayout;
